name: ABAP_740

on:
  push:
    branches: [740]

permissions:
  contents: read

jobs:
  ABAP_740:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 740
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - run: npx abaplint .github/abaplint/abap_740.jsonc
