name: create_app2abap

on:
  push:
    branches: [main, storage]

jobs:
  create_app2abap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: run transformation
        run: |
          npm ci
          npm run auto_app2abap
          npm run auto_abaplint

      - name: Open PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: auto-app2abap
          branch: auto-app2abap
